### ISSUE TITLE
I think it would be cool to have a TODO list for the glaucus project

### ISSUE THREAD

**Issue by takusuman** [glaucuslinux/glaucus#11]
This would help to add more people working together in the project.
Like, make a session in the website about what the project needs, like bugs to be fixed or ideas to be implemented.
I'd like to help. :^)

By the way, this is a really amazing project, it really have potential.

**Comment by firasuke** [comment]
I agree with what you've said; however, I'm still finalizing some details before updating the documentation and creating a TODO list (basically before opening the door to contributors).

Please look forward to it!

Thanks again!

**Comment by firasuke** [comment]
Closing for now.
