### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by joker25** [glaucuslinux/glaucus#14]
Hello, your system looks kinda interesting.

but i dont really know how to build a testsetup with it. Is there some kind of build instructions or how the folder structure has to be, to run radula to build a toolchain?

Thanks in Advance!

**Comment by firasuke** [comment]
Thanks for your interest in glaucus!

Unfortunately there are no build instructions for now, as I'm still working on the wiki, but it is as simple as cloning the repository and using `radula` to build the cross-compilation toolchain that will cross compile the final system:

```
git clone --recursive https://github.com/glaucuslinux/glaucus

cd glaucus/radula
./radula -b b t
./radula -b b x
```

You can also use `radula` to generate a bootable QEMU image:

```
sudo ./radula -b b i
```

In the future, I will be providing prebuilt toolchain tarballs to further speed up the process.

Hope that helps, let me know if you have more questions!
