### ISSUE TITLE
No boot

### ISSUE THREAD

**Issue by edsonblwolf** [glaucuslinux/glaucus#16]
![Captura de tela_2022-11-10_04-11-58](https://user-images.githubusercontent.com/50527894/201036638-9e3820a2-3355-4b14-be99-c71f754aecff.png)

**Comment by firasuke** [comment]
Please run the image using the instructions provided on the release page:

```
qemu-system-x86_64 -enable-kvm -cpu host -hda glaucus-s6-x86-64-v3-11102022.img -m 256M
```
