### ISSUE TITLE
I tried to run the latest version, QEMU kept saying "no bootable disk"

### ISSUE THREAD

**Issue by xplshn** [glaucuslinux/glaucus#19]
I tried IMG, and the 2 ISO methods.

**Comment by firasuke** [comment]
Oh, that's unfortunate. Please make sure you are using the correct method for the correct image file type.

If you downloaded the `.img` image file the following command must be used:

```
qemu-system-x86_64 \
  -machine q35,accel=kvm \
  -cpu host \
  -m 1G \
  -name glaucus \
  -drive file=glaucus-s6-x86-64-v3-20231002.img,format=raw \
  -display gtk,gl=on \
  -vga qxl \
  -rtc base=localtime
```

And if you downloaded the `.iso` image file, then the following command must be used for BIOS/MBR boot:

```
qemu-system-x86_64 \
  -machine q35,accel=kvm \
  -cpu host \
  -boot order=d \
  -m 1G \
  -name glaucus \
  -cdrom glaucus-s6-x86-64-v3-20231002.iso \
  -display gtk,gl=on \
  -vga qxl \
  -rtc base=localtime
```

And if you want to boot the `.iso` image file with UEFI/GPT, then run the following command:

```
qemu-system-x86_64 \
  -machine q35,accel=kvm \
  -cpu host \
  -boot order=d \
  -m 1G \
  -name glaucus \
  -cdrom glaucus-s6-x86-64-v3-20231002.iso \
  -display gtk,gl=on \
  -vga qxl \
  -rtc base=localtime \
  -bios /usr/share/ovmf/x64/OVMF.fd
```

**Comment by xplshn** [comment]
I am sure, I also asked a friend of mine to try with VMware, I gave him the link to this repo, and he's a sysadmin, I doubt he's mistaken too. I also tried with OVMF, both complained about the IMG and ISO not being valid.

**Comment by xplshn** [comment]
I didn't work on Boxes, which I tried in a flatpak because my system is Musl and not Glibc, but it didn't work neither, I used the commands provided in the releases but also tried from scratch when those didn't work.

**Comment by firasuke** [comment]
I appreciate your feedback on this. Can you specify in detail what image file type did you use and what command(s) did you run?

**Comment by firasuke** [comment]
Just a quick check, did you decompress the image file type before running it?

**Comment by xplshn** [comment]
Of course, I used the command you provided in the release

**Comment by firasuke** [comment]
> Of course, I used the command you provided in the release

I see.

Can you please link to the release you used? and what commands did you run?

**Comment by firasuke** [comment]
@xplshn You are correct, I have simplified the decompression instruction to only use `zstd` instead of `tar` and `zstd`, and I forgot that for this release I used `tar`.

The decompression command should be:

```
tar --use-compress-program 'zstd -d -T0 --long=31' -xvf glaucus-s6-x86-64-v3-20231002.img.zst -C .
```

This has been fixed for upcoming releases, thanks for reporting it for this release though.
