### ISSUE TITLE
Booting baremetal? [Athlon X2 AMD64]

### ISSUE THREAD

**Issue by xplshn** [glaucuslinux/glaucus#21]

**Comment by firasuke** [comment]
Can you provide more details?

**Comment by xplshn** [comment]
I am seeking guidance on how to install Glaucus to a hard drive and boot from it directly

**Comment by firasuke** [comment]
I see. Unfortunately glaucus is not yet available for installation in its current state.

**Comment by firasuke** [comment]
> I understand, but what is keeping us from installing it baremetal?

Not much actually, just some fine-tuning here and there.

> I have a machine set up with an amber CRT, I was looking for a very Unixy feeling distro, not much is needed for my use case, just toybox + musl is quite okay for me, I don't even need a package manager since I have mine (1360+ statically binaries in the repos of https://github.com/xplshn/bigdl)

That is really cool. I'm interested in seeing how glaucus would perform for such use case.

**Comment by xplshn** [comment]
Thanks for this awesome project btw, I will keep trying it seems

**Comment by firasuke** [comment]
> Thanks for this awesome project btw, I will keep trying it seems

I am glad you liked it! Don't forget to join the [Discord server](https://discord.gg/nDKNmNc).

Also, feel free to leave this issue open if you needed help with your trials (please do keep in mind glaucus only targets `x86-64-v3`).
