### ISSUE TITLE
The boot image can not be started by openstack qemu and kvm

### ISSUE THREAD

**Issue by shaohaiyang** [glaucuslinux/glaucus#22]
1. download the image and decompress
`zstd -d -T0 --long glaucus-s6-x86-64-v3-20240404.img.zst
`

![WX20240531-171534](https://github.com/glaucuslinux/glaucus/assets/2763056/d0c70dd6-c75f-4998-903e-592252bc6dac)

**Comment by firasuke** [comment]
What commands are you using to run the image?

**Comment by firasuke** [comment]
Is this issue still relevant with the [latest release](https://github.com/glaucuslinux/glaucus/releases/tag/20241026)?

**Comment by firasuke** [comment]
Closing...
