### ISSUE TITLE
Discord, IRC?

### ISSUE THREAD

**Issue by protonesso** [glaucuslinux/glaucus#4]
That would be great to have irc or discord server

**Comment by firasuke** [comment]
I agree with your kind suggestion.

I was actually planning on adding a support section once I'm done working on the second big release of glaucus (which should be coming soon).

The support section will have the following:
- IRC
- Discord
- Gitter
- Telegram
- Reddit
- Dedicated Forum?

Lemme know if you have any other suggestion.

**Comment by protonesso** [comment]
Matrix

**Comment by firasuke** [comment]
Here are the currently available support links:

1-   [Discord Server](https://discord.gg/gZSHj65)
2-   [Subreddit](https://www.reddit.com/r/glaucus)
3-   [Gitter](https://gitter.im/glaucuslinux/glaucus)
