### ISSUE TITLE
Cerata list for atlanticus

### ISSUE THREAD

**Issue by sdsddsd1** [glaucuslinux/glaucus#6]
Hello,
I am looking for the cerata of your minimal Wayland setup atlanticus, but I couldn't find it. Would you mind to share these?
Greetings

**Comment by firasuke** [comment]
Hey there!

Actually I'm still working on the base system now, so no graphics stack is available at the moment.

It will be a while before a fully functional graphics stack based on wayland is ready.

**Comment by sdsddsd1** [comment]
Ok, I will visit again then.
Thanks anyway.

**Comment by sdsddsd1** [comment]
Ok, I will visit again then.
Thanks anyway.

**Comment by firasuke** [comment]
Yes, please do.

You're welcome.

**Comment by sdsddsd1** [comment]
Ok here I visit again.  
I have figured out two wayland configurations with the least X dependencies possible. You can read a short documentation about it at my personal wayland repository for KISS Linux.
[Link](https://github.com/sdsddsd1/mywayland)

**Comment by firasuke** [comment]
Interesting indeed.

Thank for the link, I'll examine it later on when I'm working on the graphics stack.

**Comment by sdsddsd1** [comment]
You´re welcome.
