### ISSUE TITLE
install is not working as in the wiki page

### ISSUE THREAD

**Issue by rapha8l** [glaucuslinux/glaucus#9]
Seems the scripts folder has been removed.
Thanks

**Comment by firasuke** [comment]
Thank you for your interest in glaucus.

The scripts folder has been removed as most of its functionality was ported into [radula](https://www.github.com/glaucuslinux/radula) (which is glaucus's upcoming package manager).

The project is currently undergoing big changes, and the current instructions are obsolete and will be updated once the changes have been made.

**Comment by rapha8l** [comment]
Got it !
Thanks

**Comment by firasuke** [comment]
You're welcome, thanks for your interest!

**Comment by firasuke** [comment]
You're most welcome!
